---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "edcdb33cd78b9810254cfbe3dc5b7a4c42e9742f"
    fabric8.io/git-branch: "main"
    fabric8.io/git-url: "https://github.com/likhia/Camel7AmqStreamService.git"
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: "camel-ose-springboot-xml"
    provider: "fabric8"
    version: "1.0.0-SNAPSHOT"
    group: "org.mycompany"
  name: "camel-ose-springboot-xml"
spec:
  ports:
  - name: "http"
    port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: "camel-ose-springboot-xml"
    provider: "fabric8"
    group: "org.mycompany"
