---
apiVersion: "route.openshift.io/v1"
kind: "Route"
metadata:
  annotations:
    fabric8.io/git-commit: "edcdb33cd78b9810254cfbe3dc5b7a4c42e9742f"
    fabric8.io/git-branch: "main"
    fabric8.io/git-url: "https://github.com/likhia/Camel7AmqStreamService.git"
  labels:
    expose: "true"
    app: "camel-ose-springboot-xml"
    provider: "fabric8"
    version: "1.0.0-SNAPSHOT"
    group: "org.mycompany"
  name: "camel-ose-springboot-xml"
spec:
  port:
    targetPort: 8080
  to:
    kind: "Service"
    name: "camel-ose-springboot-xml"
